[package]
name = "rust-1st"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
nu-ansi-term = "0.49"
once_cell = "1.18"
